= License
:encoding: utf-8
:lang: en
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ./docs/res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


ifdef::env-github,env-vscode[]
link:LICENSE.adoc[Japanese] / link:LICENSE.en.adoc[English]
endif::env-github,env-vscode[]


== LICENSE

This software depends on the following software and does not work alone.

Live2D Cubism SDK::
This library is used to run files created in Live2D Editor.

Live2D Cubism NativeFramework::
A library for making the SDK easier to use.

Therefore, you, as a user, must observe the following in the process of building and using this software.


=== Live2D Open Software License
Live2D Cubism Components is available under Live2D Open Software License.

* link:https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html[Live2D Open Software License Agreement]
* link:https://www.live2d.com/eula/live2d-open-software-license-agreement_jp.html[Live2D Open Software 使用許諾契約書]
* link:https://www.live2d.com/eula/live2d-open-software-license-agreement_cn.html[Live2D Open Software 使用授权协议]

When publishing applications created with GDCubism, the following agreements must be observed.


=== Live2D Proprietary Software License
Live2D Cubism Core is available under Live2D Proprietary Software License.


* link:https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html[Live2D Proprietary Software License Agreement]
* link:https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_jp.html[Live2D Proprietary Software 使用許諾契約書]
* link:https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_cn.html[Live2D Proprietary Software 使用授权协议]


[IMPORTANT]
====
Only the portion of the GDCubism repository that is publicly available is covered by the GDCubism license.

Please note that it will be linked to Live2D's library during the build process.
====


=== About licensing information
==== Live2D Cubism SDK
==== Cubism Native Framework

For Live2D Cubism Components and CubismNativeFramework, please refer to the license information on the following page.

* link:https://github.com/Live2D/CubismNativeFramework[]


==== GDCubism

MIT License

Copyright (c) 2023 MizunagiKB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

