= License
:encoding: utf-8
:lang: ja
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ./docs/res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


ifdef::env-github,env-vscode[]
link:LICENSE.adoc[Japanese] / link:LICENSE.en.adoc[English]
endif::env-github,env-vscode[]


== ライセンスについて

このソフトウェアは以下のソフトウェアに依存しており単品では動作しません。

Live2D Cubism SDK::
Live2D Editorで作成されたファイルをを動かすためのライブラリです。

Live2D Cubism NativeFramework::
SDKを使いやすくするためのライブラリです。

そのため利用者の方がビルドを行う過程において、以下の内容を守る必要があります。

* link:https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html[Live2D Open Software License Agreement]
* link:https://www.live2d.com/eula/live2d-open-software-license-agreement_jp.html[Live2D Open Software 使用許諾契約書]
* link:https://www.live2d.com/eula/live2d-open-software-license-agreement_cn.html[Live2D Open Software 使用授权协议]

また、GDCubismで作られたアプリケーションを公開する場合には、以下の契約を守る必要があります。

* link:https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html[Live2D Proprietary Software License Agreement]
* link:https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_jp.html[Live2D Proprietary Software 使用許諾契約書]
* link:https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_cn.html[Live2D Proprietary Software 使用授权协议]


[IMPORTANT]
====
GDCubismのリポジトリで公開されている部分のみがGDCubismのライセンス適用範囲となります。
ビルドするとLive2D社のライブラリとリンクされたバイナリとなる点にご注意ください。
====


=== ライセンス情報について
==== Live2D Cubism SDK
==== Cubism Native Framework

Live2D Cubism Components, CubismNativeFrameworkについては以下のページにある license 情報を参照してください。

* link:https://github.com/Live2D/CubismNativeFramework[]



==== GDCubism

MIT License

Copyright (c) 2023 MizunagiKB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

