= API Reference
:author: MizunagiKB
:copyright: 2023 MizunagiKB <mizukb@live.jp>
:doctype: book
:toc:
:toclevels: 3
:lang: ja
:encoding: utf-8
:stylesdir: ./res/theme/css
:stylesheet: adoc-golo.css
:source-highlighter: highlight.js
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


== class: GDCubismEffectCustom

このクラスを継承することで、 link:API_gd_cubism_user_model.ja.adoc[_GDCubismUserModel_] に対して任意の操作を行えます。


=== Properties
=== Methods

[cols="2",frame=none,grid=none]
|===
>|void <|_cubism_init() virtual
>|void <|_cubism_term() virtual
>|void <|_cubism_process(model: link:API_gd_cubism_user_model.ja.adoc[GDCubismUserModel], delta: float) virtual
|===


=== Signals
=== Enumerations
=== Constants
=== Property Descriptions
=== Method Descriptions

[[id-method-_cubism_init]]
void _cubism_init() virtual::
この関数をオーバーロードすることで、クラスを開始する機会が得られます。
 +
 +
関数は link:API_gd_cubism_user_model.ja.adoc[GDCubismUserModel] が必要になったタイミングで一度だけ呼び出されます。

WARNING: 親クラスに link:API_gd_cubism_effect.ja.adoc[GDCubismEffect] クラスの追加／削除が発生した場合、改めて <<id-method-_cubism_term,__custom_term__>> 関数と <<id-method-_cubism_init,__custom_init__>> 関数が呼び出されます。


[[id-method-_cubism_term]]
void _cubism_term() virtual::
この関数をオーバーロードすることで、クラスを終了する機会が得られます。
 +
 +
関数は link:API_gd_cubism_user_model.ja.adoc[GDCubismUserModel] が不要になったタイミングで一度だけ呼び出されます。

WARNING: 親クラスに link:API_gd_cubism_effect.ja.adoc[GDCubismEffect] クラスの追加／削除が発生した場合、改めて <<id-method-_cubism_term,__custom_term__>> 関数と <<id-method-_cubism_init,__custom_init__>> 関数が呼び出されます。


[[id-method-_cubism_process]]
void _cubism_process(model: link:API_gd_cubism_user_model.ja.adoc[GDCubismUserModel], delta: float) virtual::

親クラスの更新機会に合わせて呼び出されます。
