= GDCubismUserModel
:encoding: utf-8
:lang: ja
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ../../res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


== Desc

Live2Dモデルを読み込み、表示に必要な _Texture_ を生成したり操作を行うための _SubVieport_ 継承クラスです。



== Properties

[cols="3",frame=none,grid=none]
|===
>|Vector2 <|<<id-property-adjust_position,adjust_position>> |[default: Vector2(0, 0)]
>|float <|<<id-property-adjust_scale,adjust_scale>> |[default: 1.0]
>|String <|<<id-property-assets,assets>> |[default: ""]
>|bool <|<<id-property-auto_scale,auto_scale>> |[default: true]
>|bool <|<<id-property-load_expressions,load_expressions>> |[default: true]
>|bool <|<<id-property-load_motions,load_motions>> |[default: true]
>|Vector2i <|<<id-property-mask_viewport_size>> |[default: Vector2i(0, 0)]
>|ParameterMode <|<<id-property-parameter_mode,parameter_mode>> |[default: 0]
>|bool <|<<physics_evaluate>> |[default: true]
>|MotionProcessCallback <|<<id-property-playback_process_mode,playback_process_mode>> |[default: 1]
>|bool <|<<pose_update>> |[default: true]
>|Shader <|<<id-property-shader_add,shader_add>> |
>|Shader <|<<id-property-shader_mask,shader_mask>> |
>|Shader <|<<id-property-shader_mask_add,shader_mask_add>> |
>|Shader <|<<id-property-shader_mask_add_inv,shader_mask_add_inv>> |
>|Shader <|<<id-property-shader_mask_mix,shader_mask_mix>> |
>|Shader <|<<id-property-shader_mask_mix_inv,shader_mask_mix_inv>> |
>|Shader <|<<id-property-shader_mask_mul,shader_mask_mul>> |
>|Shader <|<<id-property-shader_mask_mul_inv,shader_mask_mul_inv>> |
>|Shader <|<<id-property-shader_mix,shader_mix>> |
>|Shader <|<<id-property-shader_mul,shader_mul>> |
>|float <|<<id-property-speed_scale,speed_scale>> |[default: 1.0]
|===


== Methods

[cols="2",frame=none,grid=none]
|===
>|void <|advance(delta: float)
>|void <|clear()
>|moc3FileFormatVersion <|csm_get_latest_moc_version()
>|moc3FileFormatVersion <|csm_get_moc_version()
>|Dictionary <|csm_get_version()
>|Dictionary <|get_canvas_info()
>|Array <|get_cubism_motion_queue_entries()
>|Array <|get_expressions()
>|Array <|get_hit_areas()
>|Dictionary <|get_meshes()
>|Dictionary <|get_motions()
>|Array <|get_parameters()
>|Array <|get_part_opacities()
>|void <|start_expression(expression_id: String)
>|GDCubismMotionQueueEntryHandle <|start_motion(group: String, no: int, priority: Priority)
>|GDCubismMotionQueueEntryHandle <|start_motion_loop(group: String, no: int, priority: Priority, loop: bool, loop_fade_in: bool)
>|void <|stop_expression()
>|void <|stop_motion()
|===


== Signals

motion_event(value: String)::
_Motion_ に埋め込まれたイベント時刻のタイミングで呼び出されます。

.Example
[source,gdscript]
----
func _on_motion_event(value: String):
    print(value)

func _ready():
    $GDCubismUserModel.motion_event.connect(_on_motion_event)
----

motion_finished()::
_Motion_ が再生終了したタイミングで呼び出されます。

.Example
[source,gdscript]
----
func _on_motion_finished(value: String):
    print(value)

func _ready():
    $GDCubismUserModel.motion_event.connect(_on_motion_event)
----


== Enumerations

[[id-enum-moc3_file_format_version]]
enum moc3FileFormatVersion::
* CSM_MOC_VERSION_UNKNOWN = 0 +
不明または読み込み失敗
* CSM_MOC_VERSION_30 = 1 +
moc3 file version 3.0.00 から 3.2.07
* CSM_MOC_VERSION_33 = 2 +
moc3 file version 3.3.00 から 3.3.03
* CSM_MOC_VERSION_40 = 3 +
moc3 file version 4.0.00 から 4.1.05
* CSM_MOC_VERSION_42 = 4 +
moc3 file version 4.2.00 から 4.2.02
* CSM_MOC_VERSION_50 = 5 +
moc3 file version 5.0.00以上


[[id-enum-priority]]
enum Priority::
* PRIORITY_NONE = 0
* PRIORITY_IDLE = 1
* PRIORITY_NORMAL = 2
* PRIORITY_FORCE = 3 +
強制的に切り替わります。


enum ParameterMode::
* FULL_PARAMETER = 0 +
<<id-method-start_motion,_start_motion_>> 関数で指定した _Motion_ を再生する時に指定します。 +
この指定がされているときは xref:./gd_cubism_parameter.adoc[] による操作は行えません。
* NONE_PARAMETER = 1 +
<<id-method-start_motion,_get_parameters_>> 関数で取得した xref:./gd_cubism_parameter.adoc[] を使用して、Live2Dモデルを操作する場合に指定します。 +
この指定がされているときは <<id-method-start_motion,_start_motion_>> 関数でモーション再生は行えません。


enum MotionProcessCallback::
* PHYSICS = 0 +
アニメーションの更新処理を __physics_process_ 関数内で行います。物理シミュレーションとインタラクションさせたい時に使用します。
* IDLE = 1 +
アニメーションの更新処理を __process_ 関数内で行います。
* MANUAL = 2 +
アニメーションの更新処理を行いません。アニメーションを処理するには <<id-method-advance,_advance_>> 関数を使用します。


== Property Descriptions

[[id-property-adjust_position]]
Vector2 adjust_position [default: Vector2(0, 0)]::
Live2Dモデルの描画位置を変更します。 +
GDCubismは自身が持つSubViewport内にLive2Dモデルの描画を行います。 +
このパラメータを調整する事でLive2Dモデルの一部をクローズアップしたり auto_scale された描画結果がうまく描画されない場合に利用してください。


[[id-property-adjust_scale]]
float adjust_scale [default: 1.0]::
Live2Dモデルの描画サイズを変更します。 +
GDCubismは自身が持つSubViewport内にLive2Dモデルの描画を行います。 +
このパラメータを調整する事でLive2Dモデルの描画サイズを自由に変更できます。


[[id-property-assets]]
String assets [default: ""]::
*.model3.json 拡張子のファイルを指定することでLive2Dモデルを読み込みます。
ファイルを指定すると即座にファイルが読み込まれます。 +
Live2Dモデルを切り替えたい場合は新しいファイルを指定するだけで切り替える事が出来ます。


[[id-property-auto_scale]]
bool auto_scale [default: true]::
_GDCubismUserModel_ は、自分自身に指定された _SubViewport_ サイズ内に収まる様にLive2Dモデルを描画しようとします。そのためLive2Dモデルの製作者が意図しない結果になってしまう場合があります。 +
 +
このチェックを外すことで、スケーリングなしで表示を行います。


[[id-property-load_expressions]]
bool load_expressions [default: true]::
_false_ にすると、 Live2D Modelの読み込み時に _Expression_ の読み込みを行いません。


[[id-property-load_motions]]
bool load_motions [default: true]::
_false_ にすると、 Live2D Modelの読み込み時に _Motion_ の読み込みを行いません。


[[id-property-mask_viewport_size]]
Vector2i mask_viewport_size [default: Vector2i(0, 0)]::
Live2Dモデルでマスク画像を必要とする場合の解像度を指定します。
+
x, y のどちらかに 0 が設定されている場合は、 GDCubismUserModel に設定されている Viewport と同じサイズが使用されます。
+
解像度を下げるとGPUメモリの消費を抑える事が出来ます。512x512程度のサイズより小さくしてしまうと、マスクの適用場所によっては描画品質に問題が生じる可能性があります。
+
この画像の縦横比は GDCubismUserModel の Viewport と同じ比率となるようにしてください。1024x512 であれば、512x256 や 128x64 といった数値です。
+
GDCubism は Viewport と同じ比率であることを前提に描画を行うため、正しい比率以外の場合は望ましい結果を得る事が出来ません。


[[id-property-parameter_mode]]
ParameterMode parameter_mode [default: 0]::
現在保持しているLive2Dモデルのコントロール方法を指定します。


[[id-property-physics_evaluate]]
bool physics_evaluate [default: true]::
_false_ にすると、物理計算を行わなくなります。


[[id-property-playback_process_mode]]
MotionProcessCallback playback_process_mode [default: 1]::
現在保持しているLive2Dモデルの再生方法を指定します。


[[id-property-pose_update]]
bool pose_update [default: true]::
_false_ にすると、ポーズグループに指定された描画パーツ同士で透明度の計算を行わなくなります。 +
全ての透明度計算を手動で行いたい場合は _false_ にしてください。


[[id-property-shader_add]]
Shader shader_mask_add::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_norm_add.gdshader[]
----


[[id-property-shader_mask]]
Shader shader_mask::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask.gdshader[]
----


[[id-property-shader_mask_add]]
Shader shader_mask_add::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask_add.gdshader[]
----


[[id-property-shader_mask_add_inv]]
Shader shader_mask_add_inv::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask_add_inv.gdshader[]
----


[[id-property-shader_mask_mix]]
Shader shader_mask_mix::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask_mix.gdshader[]
----


[[id-property-shader_mask_mix_inv]]
Shader shader_mask_mix_inv::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask_mix_inv.gdshader[]
----


[[id-property-shader_mask_mul]]
Shader shader_mask_mul::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask_mul.gdshader[]
----


[[id-property-shader_mask_mul_inv]]
Shader shader_mask_mul_inv::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_mask_mul_inv.gdshader[]
----


[[id-property-shader_mix]]
Shader shader_mix::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_norm_mix.gdshader[]
----


[[id-property-shader_mul]]
Shader shader_mul::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source,,numlines]
----
include::example$2d_cubism_norm_mul.gdshader[]
----


[[id-property-speed_scale]]
floats speed_scale [default: 1.0]::
現在保持しているLive2Dモデルの再生速度を指定します。


== Method Descriptions

[[id-method-advance]]
void advance(delta: float)::
アニメーションを指定した _delta_ 時間（単位は秒数）だけ進めます。
+
deltaには 0.0 以上の値を指定してください。


[[id-method-clear]]
void clear()::
この関数は操作の一貫性向上を目的に削除されました。 +
同様の操作を行うには _assets_ プロパティに "" をセットしてください。


[[id-method-csm_get_latest_moc_version]]
<<id-enum-moc3_file_format_version,moc3FileFormatVersion>> csm_get_latest_moc_version()::
GDCubismUserModelが読み込める最新のファイルバージョンを戻します。


[[id-method-csm_get_moc_version]]
<<id-enum-moc3_file_format_version,moc3FileFormatVersion>> csm_get_moc_version()::
読み込まれたmoc3ファイルのバージョンを戻します。


[[id-method-csm_get_version]]
Dictionary csm_get_version()::
GDCubism が使用している Cubism Native SDK Core のバージョン番号を _Dictionary_ 形式で戻します。 +
+
version: int:::
_csmVersion_ 関数が戻す値がそのまま格納されています。
major: int:::
versionからメジャーバージョンのみを抜き出した値が格納されています。
minor: int:::
versionからマイナーバージョンのみを抜き出した値が格納されています。
patch: int:::
versionからパッチ番号のみを抜き出した値が格納されています。


[[id-method-get_canvas_info]]
Dictionary get_canvas_info()::
_Dictionary_ 形式で以下の情報を戻します。 +
+ 
size_in_pixels: Vector2:::
読み込んだLive2Dモデルのキャンバスの幅と高さをピクセル数で戻します。
origin_in_pixels: Vector2:::
読み込んだLive2Dモデルの中心位置をピクセル数で戻します。
pixels_per_unit: float:::
読み込んだLive2Dモデルの _pixelsPerUnit_ を戻します。


[[id-method-get_cubism_motion_queue_entries]]
Array get_cubism_motion_queue_entries()::
現在再生中の _Motion_ 情報を戻します。


[[id-method-get_expressions]]
Array get_expressions()::
現在保持しているLive2Dモデルから _Expression_ 一覧を戻します。
+
取得した情報は _start_expression_ 関数の引数として使用できます。


[[id-method-get_hit_areas]]
Array get_hit_areas()::
Live2Dモデルに設定されている _HitArea_ 情報を取得します。 +
配列の要素は _Dictionary_ になっており、要素として _id_ と _name_ を持ちます。 +
 +
_id_ は _mesh_ 要素を指す為、 _get_meshes_ のキーとして利用可能です。 +
 +
この関数と _get_meshes_ で得られる情報を使用する事で、 Live2Dモデルとのインタラクションを実装できます。 +
高度な処理を必要としない場合は、 _GDCubismEffectHitArea_ クラスを使用する事で、簡単に利用する事が可能です。


[[id-method-get_meshes]]
Dictionary get_meshes()::
現在の Motion 状態で使用されている _MeshInstance_ の _ArrayMesh_ 情報を取得します。 +
 +
この _Dictionary_ が持つキーは _GDCubismUserModel_ が生成する _MeshInstance_ の名前と同一です。取得できる情報は内部で使用されている _ArrayMesh_ です。
 +
以下の様な形で使用することができます。


[source, gdscript]
----
var dict_mesh: Dictionary = model.get_meshes()
var ary_mesh: ArrayMesh = dict_mesh[art_mesh_name]
var ary_surface: Array = ary_mesh.surface_get_arrays(0)

var mesh_vertex: PackedVector2Array = ary_surface[ArrayMesh.ARRAY_VERTEX]
var mesh_tex_uv: PackedVector2Array = ary_surface[ArrayMesh.ARRAY_TEX_UV]
var mesh_index: PackedInt32Array = ary_surface[ArrayMesh.ARRAY_INDEX]
----

CAUTION: _get_meshes_ は v0.1 で追加された実験的な関数です。今後仕様が変更されたり削除される可能性がある事に注意してください。


[[id-method-get_motions]]
Dictionary get_motions()::
現在保持しているLive2Dモデルから _Motion_ 一覧を戻します。 +
戻される _Dictionary_ は _group_ とその中に含まれるモーション数です。
 +
 +
全てのモーションを列挙する場合は、以下の様に記述します。

[source, gdscript]
----
var dict_motion = $GDCubismUserModel.get_motions()
for group in dict_motion.keys():
    for no in dict_motion[group]:
        print("group: %s, no: %d" % [group, no])
----


[[id-method-get_parameters]]
Array get_parameters()::
現在保持しているLive2Dモデルを操作するためのクラスを取得します。


[[id-method-get_part_opacities]]
Array get_part_opacities()::
現在保持しているLive2Dモデルのパーツ透明度を操作するためのクラスを取得します。


[[id-method-start_expression]]
void start_expression(expression_id: String)::
指定した _expression_id_ を再生します。


[[id-method-start_motion]]
xref:./gd_cubism_motion_queue_entry_handle.adoc[] start_motion(group: String, no: int, priority: <<id-enum-priority,Priority>>)::
指定した _group_ と _no_ の _Motion_ を再生します。


[[id-method-start_motion_loop]]
xref:./gd_cubism_motion_queue_entry_handle.adoc[] start_motion_loop(group: String, no: int, priority: <<id-enum-priority,Priority>>)::
指定した _group_ と _no_ の _Motion_ を再生します。 +
 +
繰り返し再生を行いたい場合に指定します。 _loop_ 引数が _false_ の場合は、 _start_motion_ 関数と同じ動作となります。

[[id-method-stop_expression]]
void stop_expression()::
現在再生中の _Expression_ を停止します。


[[id-method-stop_motion]]
void stop_motion()::
現在再生中の _Motion_ を停止します。

