= Cubism for Godot Engine
:encoding: utf-8
:lang: en
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ./docs/res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


== About GDCubism

This software (GDCubism) is an **unofficial** GDExtension that makes the link:https://www.live2d.com/download/cubism-sdk/[Live2D Cubism SDK] accessible from GDScript or C#.

[NOTE]
====
This GDExtension is available for use with Godot Engine 4.1 and above. (If you wish to use it with versions 4.3 or lator, please use link:https://github.com/MizunagiKB/gd_cubism/tree/0.7[7.0])
====

Internally, GDCubism uses the link:https://github.com/Live2D/CubismNativeFramework[Cubism Native Framework] published by Live2D Inc.

Please do not contact the developer, Live2D Inc., regarding GDCubism.


== Support platform

[cols="2",frame=none,grid=none]
|===
>|Windows
a|
* x86_32
* x86_64

>|macOS
a|
* x86_64
* arm64
* universal

>|Linux
a|
* x86_64

>|iOS
a|
* arm64 (experimental)
* universal (experimental)

>|Android
a|
* armv7 (experimental)
* arm64v8 (experimental)
|===


== About LICENSE

[NOTE]
====
GDCubism, when linked with dependent external libraries, results in licenses with different usage conditions. +
If you are considering distributing or selling a product incorporating GDCubism, please check the licenses listed on the following page.
====

* xref:en/license.adoc[]


== How to build

* xref:en/build.adoc[]


== Usage

* xref:en/usage.adoc[]


== Ralated link

* link:https://www.live2d.com/[Live2D Cubism]
* link:https://www.live2d.com/download/cubism-sdk/[Live2D Cubism SDK]
* link:https://github.com/Live2D[Live2D (GitHub)]
* link:https://github.com/Live2D/CubismNativeFramework[CubismNativeFramework (GitHub)]
* link:https://github.com/MizunagiKB/gd_cubism[MizunagiKB / gd_cubism (GitHub)]

