= API Reference
:author: MizunagiKB
:doctype: book
:toc:
:toclevels: 3
:lang: ja
:encoding: utf-8
:stylesdir: ./res/theme/css
:stylesheet: adoc-golo.css
:source-highlighter: highlight.js
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


== class: GDCubismUserModel

Live2Dモデルを読み込み、表示に必要な _Texture_ を生成したり操作を行うための _SubVieport_ 継承クラスです。


=== Properties

[cols="3",frame=none,grid=none]
|===
>|String <|<<id-property-assets,assets>> |[default: ""]
>|bool <|<<id-property-auto_scale,auto_scale>> |[default: true]
>|ParameterMode <|<<id-property-<parameter_mode,parameter_mode>> |[default: 0]
>|MotionProcessCallback <|<<id-property-playback_process_mode,playback_process_mode>> |[default: 1]
>|Shader <|<<id-property-shader_mask,shader_mask>> |
>|Shader <|<<id-property-shader_mask_mix,shader_mask_mix>> |
>|Shader <|<<id-property-shader_mask_mix_inv,shader_mask_mix_inv>> |
>|Shader <|<<id-property-shader_mix,shader_mix>> |
>|float <|<<id-property-speed_scale,speed_scale>> |[default: 1.0]
|===


=== Methods

[cols="2",frame=none,grid=none]
|===
>|void <|advance(delta: float)
>|void <|clear()
>|moc3FileFormatVersion <|csm_get_latest_moc_version()
>|moc3FileFormatVersion <|csm_get_moc_version()
>|Dictionary <|csm_get_version()
>|Dictionary <|get_canvas_info()
>|Array <|get_cubism_motion_queue_entries()
>|Array <|get_expressions()
>|Array <|get_hit_areas()
>|Dictionary <|get_motions()
>|Array <|get_parameters()
>|Array <|get_part_opacities()
>|void <|start_expression(expression_id: String)
>|GDCubismMotionQueueEntryHandle <|start_motion(group: String, no: int, priority: Priority)
>|GDCubismMotionQueueEntryHandle <|start_motion_loop(group: String, no: int, priority: Priority, loop: bool, loop_fade_in: bool)
>|void <|stop_expression()
>|void <|stop_motion()
|===


=== Signals

motion_event(value: String)::
_Motion_ に埋め込まれたイベント時刻のタイミングで呼び出されます。

.Example
[source,gdscript]
----
func _on_motion_event(value: String):
    print(value)

func _ready():
    $GDCubismUserModel.motion_event.connect(_on_motion_event)
----

motion_finished()::
_Motion_ が再生終了したタイミングで呼び出されます。

.Example
[source,gdscript]
----
func _on_motion_finished(value: String):
    print(value)

func _ready():
    $GDCubismUserModel.motion_event.connect(_on_motion_event)
----

CAUTION: _motion_finished_ シグナルは、現在カスタムビルドを行った時のみ使用可能です。
 +
カスタムビルドの方法については、 link:BUILD.adoc[] を参照してください。

=== Enumerations

[[id-enum-moc3_file_format_version]]
enum moc3FileFormatVersion::
* CSM_MOC_VERSION_UNKNOWN = 0 +
不明または読み込み失敗
* CSM_MOC_VERSION_30 = 1 +
moc3 file version 3.0.00 から 3.2.07
* CSM_MOC_VERSION_33 = 2 +
moc3 file version 3.3.00 から 3.3.03
* CSM_MOC_VERSION_40 = 3 +
moc3 file version 4.0.00 から 4.1.05
* CSM_MOC_VERSION_42 = 4 +
moc3 file version 4.2.00 から 4.2.02
* CSM_MOC_VERSION_50 = 5 +
moc3 file version 5.0.00以上


[[id-enum-priority]]
enum Priority::
* PRIORITY_NONE = 0
* PRIORITY_IDLE = 1
* PRIORITY_NORMAL = 2
* PRIORITY_FORCE = 3 +
強制的に切り替わります。


enum ParameterMode::
* FULL_PARAMETER = 0 +
<<id-method-start_motion,_start_motion_>> 関数で指定した _Motion_ を再生する時に指定します。 +
この指定がされているときは link:API_gd_cubism_parameter.ja.adoc[_GDCubismParameter_] による操作は行えません。
* NONE_PARAMETER = 1 +
<<id-method-start_motion,_get_parameter_>> 関数で取得した link:API_gd_cubism_parameter.ja.adoc[_GDCubismParameter_] を使用して、Live2Dモデルを操作する場合に指定します。 +
この指定がされているときは <<id-method-start_motion,_start_motion_>> 関数でモーション再生は行えません。


enum MotionProcessCallback::
* PHYSICS = 0 +
アニメーションの更新処理を __physics_process_ 関数内で行います。物理シミュレーションとインタラクションさせたい時に使用します。
* IDLE = 1 +
アニメーションの更新処理を __process_ 関数内で行います。
* MANUAL = 2 +
アニメーションの更新処理を行いません。アニメーションを処理するには <<id-method-advance,_advance_>> 関数を使用します。


=== Property Descriptions

[[id-property-assets]]
String assets [default: ""]::
*.model3.json 拡張子のファイルを指定することでLive2Dモデルを読み込みます。
ファイルを指定すると即座にファイルが読み込まれます。 +
内部で _clear_ 関数を呼び出しているため、Live2Dモデルを切り替えたい場合は新しいファイルを指定するだけで切り替える事が出来ます。


[[id-property-auto_scale]]
bool auto_scale [default: true]::
_GDCubismUserModel_ は、自分自身に指定された _SubViewport_ サイズ内に収まる様にLive2Dモデルを描画しようとします。そのためLive2Dモデルの製作者が意図しない結果になってしまう場合があります。 +
 +
このチェックを外すことで、スケーリングなしで表示を行います。


[[id-property-parameter_mode]]
ParameterMode parameter_mode [default: 0]::
現在保持しているLive2Dモデルのコントロール方法を指定します。


[[id-property-playback_process_mode]]
MotionProcessCallback playback_process_mode [default: 1]::
現在保持しているLive2Dモデルの再生方法を指定します。


[[id-property-shader_mask]]
Shader shader_mask_mix::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source, numlines]
----
include::../demo/addons/gd_cubism/res/shader/2d_cubism_mask.gdshader[]
----


[[id-property-shader_mask_mix]]
Shader shader_mask_mix::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source, numlines]
----
include::../demo/addons/gd_cubism/res/shader/2d_cubism_mask_mix.gdshader[]
----


[[id-property-shader_mask_mix_inv]]
Shader shader_mask_mix_inv::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source, numlines]
----
include::../demo/addons/gd_cubism/res/shader/2d_cubism_mask_mix_inv.gdshader[]
----


[[id-property-shader_mix]]
Shader shader_mix::
Live2Dモデルの描画に使用する _shader_ を指定します。 +
既定では以下の内容の _shader_ が使用されます。

[source, numlines]
----
include::../demo/addons/gd_cubism/res/shader/2d_cubism_norm_mix.gdshader[]
----


[[id-property-speed_scale]]
floats speed_scale [default: 1.0]::
現在保持しているLive2Dモデルの再生速度を指定します。


==== Method Descriptions

[[id-method-advance]]
void advance(delta: float)::
アニメーションを指定した _delta_ 時間（単位は秒数）だけ進めます。
+
deltaには 0.0 以上の値を指定してください。


[[id-method-clear]]
void clear()::
現在保持しているLive2Dモデルを破棄します。


[[id-method-csm_get_latest_moc_version]]
<<id-property-moc3_file_format_version,moc3FileFormatVersion>> csm_get_latest_moc_version()::
GDCubismUserModelが読み込める最新のファイルバージョンを戻します。


[[id-method-csm_get_moc_version]]
<<id-property-moc3_file_format_version,moc3FileFormatVersion>> csm_get_moc_version()::
読み込まれたmoc3ファイルのバージョンを戻します。


[[id-method-csm_get_version]]
Dictionary csm_get_version()::
GDCubismが使用しているCubism Native SDK Coreのバージョン番号を _Dictionary_ 形式で戻します。 +
+
* version: int +
_csmVersion_ 関数が戻す値がそのまま格納されています。
* major: int +
versionからメジャーバージョンのみを抜き出した値が格納されています。
* minor: int +
versionからマイナーバージョンのみを抜き出した値が格納されています。
* patch: int +
versionからパッチ番号のみを抜き出した値が格納されています。


[[id-method-get_canvas_info]]
Dictionary get_canvas_info()::
_Dictionary_ 形式で以下の情報を戻します。 +
+ 
* size_in_pixels: Vector2 +
読み込んだLive2Dモデルのキャンバスの幅と高さをピクセル数で戻します。
* origin_in_pixels: Vector2 +
読み込んだLive2Dモデルの中心位置をピクセル数で戻します。
* pixels_per_unit: float +
読み込んだLive2Dモデルの _pixelsPerUnit_ を戻します。


[[id-method-get_cubism_motion_queue_entries]]
Array get_cubism_motion_queue_entries()::
現在再生中の _Motion_ 情報を戻します。


[[id-method-get_expressions]]
Array get_expressions()::
現在保持しているLive2Dモデルから _Expression_ 一覧を戻します。
+
取得した情報は _start_expression_ 関数の引数として使用できます。


[[id-method-get_hit_areas]]
Array get_hit_areas()::
未実装。


[[id-method-get_motions]]
Dictionary get_motions()::
現在保持しているLive2Dモデルから _Motion_ 一覧を戻します。 +
 +
戻される _Dictionary_ は _group_ とその中に含まれるモーション数です。
 +
 +
全てのモーションを列挙する場合は、以下の様に記述します。

[source, gdscript]
----
var dict_motion = $GDCubismUserModel.get_motions()
for group in dict_motion.keys():
    for no in dict_motion[group]:
        print("group: %s, no: %d" % [group, no])
----


[[id-method-get_parameter]]
Array get_parameter()::
現在保持しているLive2Dモデルを操作するためのクラスを取得します。


[[id-method-get_part_opacity]]
Array get_part_opacity()::
現在保持しているLive2Dモデルのパーツ透明度を操作するためのクラスを取得します。


[[id-method-start_expression]]
void start_expression(expression_id: String)::
指定した _expression_id_ を再生します。


[[id-method-start_motion]]
link:API_gd_cubism_motion_queue_entry_handle[GDCubismMotionQueueEntryHandle] start_motion(group: String, no: int, priority: <<id-enum-priority,Priority>>)::
指定した _group_ と _no_ の _Motion_ を再生します。


[[id-method-start_motion_loop]]
link:API_gd_cubism_motion_queue_entry_handle[GDCubismMotionQueueEntryHandle] start_motion_loop(group: String, no: int, priority: <<id-enum-priority,Priority>>)::
指定した _group_ と _no_ の _Motion_ を再生します。 +
 +
繰り返し再生を行いたい場合に指定します。 _loop_ 引数が _false_ の場合は、 _start_motion_ 関数と同じ動作となります。

[[id-method-stop_expression]]
void stop_expression()::
現在再生中の _Expression_ を停止します。


[[id-method-stop_motion]]
void stop_motion()::
現在再生中の _Motion_ を停止します。

