= Cubism for GDScript
:encoding: utf-8
:lang: ja
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:nofooter:
:toc:
:toclevels: 3
:source-highlighter: highlight.js
:experimental:
:icons: font


link:BUILD.adoc[Japanese] / link:BUILD.en.adoc[English]


== How to build
=== Preparation before building
==== Get source code

Get the source code from the GDCubism repository.

[source, bash]
----
git clone https://github.com/MizunagiKB/gd_cubism.git
cd gd_cubism
git submodule update --init
----


==== Preparation of CubismSdkForNative

. Get Live2D Cubism SDK for Native.
.. The SDK version used by GDCubism is **Cubism 5 SDK for Native R1 beta2**.
.. Get Cubism 5 SDK for Native from Live2D's official website.
. Extract the downloaded file to _thirdparty_.

When expanded, it should look like the following.

[source, console]
----
./thirdparty
    /CubismSdkForNative-5-r.1-beta.2
        /Core
            /dll
            ...
        /Framework
            /build
            ...
----


This is a possible translation of the text in English:

==== Customizing CubismNativeFramework

GDCubism uses CubismNativeFramework, which is included in CubismSdkForNative. If you want to use the latest Framework or customize it for your own needs, you can do so by following these steps:

[source, bash]
----
pushd thirdparty
git clone https://github.com/Live2D/CubismNativeFramework.git
popd
----

CAUTION: This build has priority over the Framework in CubismSdkForNative, so please delete it when it is no longer needed.


=== Build for Windows

[NOTE]
====
The following items are required for building:

* link:https://visualstudio.microsoft.com/ja/vs/community/[VisualStudio Community], version 2019 or lator.
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====


.Installing Visual Studio caveats
****
If installing Visual Studio, make sure to enable C{plus}{plus} in the list of workflows to install.

If you've already made the mistake of installing Visual Studio without C{plus}{plus} support, run the installer again; it should present you a Modify button. Running the installer from Add/Remove Programs will only give you a Repair option, which won't let you install C{plus}{plus} tools.

link:https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html#development-in-visual-studio[Godot Engine 4.1 documentation]
****


When ready, run the build with the following command.

[source]
--
scons platform=windows arch=x86_64 target=template_debug
scons platform=windows arch=x86_64 target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.windows.debug.x86_64.dll
* libgd_cubism.windows.release.x86_64.dll


=== Build for macOS

[NOTE]
====
The following items are required for building:

* link:https://apps.apple.com/us/app/xcode/id497799835[Xcode]
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====

When ready, run the build with the following command.

[source, bash]
--
# for x86_64(intel mac)
scons platform=macos arch=x86_64 target=template_debug
scons platform=macos arch=x86_64 target=template_release
# for arm64(Apple Silicon mac)
scons platform=macos arch=arm64 target=template_debug
scons platform=macos arch=arm64 target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.macos.debug.framework
* libgd_cubism.macos.release.framework


==== Building as a universal binary

If you want to build as a universal binary, you need to create link files as follows before running scons.


[source, bash]
----
pushd thirdparty/CubismSdkForNative-5-r.1-beta.2/Core/lib/macos
mkdir universal
lipo -create arm64/libLive2DCubismCore.a x86_64/libLive2DCubismCore.a -output universal/libLive2DCubismCore.a
popd

# for universal
scons platform=macos arch=universal target=template_debug
scons platform=macos arch=universal target=template_release
----


=== Build for Linux

[NOTE]
====
The following items are required for building:

* GCC 7+, Clang 6+.
* link:https://www.python.org/downloads/windows/[Python 3.6+].
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.

For Linux, additional packages may be required for each distribution. Please refer to the Godot Engine documentation to find out what distributions require. (I checked on Ubuntu 22.04 Desktop)

* link:https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html[Compiling for Linux, *BSD]
====


When ready, run the build with the following command.

[source, bash]
--
scons platform=linux arch=x86_64 target=template_debug
scons platform=linux arch=x86_64 target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.linux.debug.x86_64.so
* libgd_cubism.linux.release.x86_64.so


=== Build for Others

The following two have only been verified to be buildable, and have not been tested for operation.

Please use them as a reference when trying to run them in each environment.


==== Build for iOS

[NOTE]
====
The following items are required for building:

* link:https://apps.apple.com/us/app/xcode/id497799835[Xcode]
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====

In cases where Xcode is used only from the command line, there may be instances where the build for iphoneos does not start.

In such cases, you can get the build to proceed by re-specifying the path to Xcode as follows:

[source, bash]
----
sudo xcode-select --switch /Applications/Xcode.app 
----

When ready, run the build with the following command.

[source, bash]
--
# for arm64
scons platform=ios arch=arm64 target=template_debug
scons platform=ios arch=arm64 target=template_release
# for universol
scons platform=ios arch=universal target=template_debug
scons platform=ios arch=universal target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.ios.debug.arm64.dylib
* libgd_cubism.ios.release.arm64.dylib
* libgd_cubism.ios.debug.universal.dylib
* libgd_cubism.ios.release.universal.dylib


==== Build for Android

[NOTE]
====
The following items are required for building:

* link:https://www.python.org/downloads/windows/[Python 3.6+].
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
* link:https://developer.android.com/studio[Android Studio]
* link:https://www.azul.com/downloads/?package=jdk#zulu[Azul Zulu: 21.28.85]
====

Assuming that you have installed Android Studio on a Windows 10 environment, follow these steps:

Launch Android Studio and open the SDK Manager. You can access the SDK Manager from the More Actions menu on the Welcome to Android Studio screen that appears when you start Android Studio.

Once the SDK Manager is open, check the following items and download them.

* SDK Platforms
** Android API 34
** Android 10("Q")
* SDK Tools
** Android SDK Build-Tools 34
** NDK (Side by side)
** Android SDK Command-line Tools (latest)
** CMake
** Android Emulator
** Android SDK Platform-Tools
** Android SDK Tools (Obsolete)

When ready, run the build with the following command.

[source, bash]
--
scons platform=android target=template_debug arch=armv7
scons platform=android target=template_release arch=armv7
scons platform=android target=template_debug arch=arm64v8
scons platform=android target=template_release arch=arm64v8
--

If the build does not start, try setting the following environment variables:

* ANDROID_SDK_ROOT ... The location where the items selected by the SDK Manager are installed
* ANDROID_HOME ... The location where the items selected by the SDK Manager are installed
* ANDROID_NDK_HOME ... The location where the NDK installed by the SDK Manager is located
* ANDROID_NDK_ROOT ... The location where the NDK installed by the SDK Manager is located

.example
[source, bash]
--
set ANDROID_SDK_ROOT=D:\Android\sdk
set ANDROID_HOME=D:\Android\sdk
set ANDROID_NDK_HOME=%ANDROID_SDK_ROOT%\ndk\26.0.10792818
set ANDROID_NDK_ROOT=%ANDROID_SDK_ROOT%\ndk\26.0.10792818
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.android.debug.arm32.so
* libgd_cubism.android.release.arm32.so
* libgd_cubism.android.debug.arm64.so
* libgd_cubism.android.release.arm64.so
