= Cubism for GDScript
:author: MizunagiKB
:copyright: 2023 MizunagiKB <mizukb@live.jp>
:doctype: book
:toc:
:toclevels: 3
:lang: ja
:encoding: utf-8
:stylesdir: ./res/theme/css
:stylesheet: adoc-golo.css
:source-highlighter: highlight.js
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


link:BUILD.adoc[Japanese] / link:BUILD.en.adoc[English]


== ビルド方法
=== ビルド前の準備
==== ソースコードの取得と準備

[source, bash]
----
git clone https://github.com/MizunagiKB/gd_cubism.git
cd gd_cubism
git submodule update --init
----


==== CubismSdkForNativeの入手と配置

Live2D Cubism SDK for Nativeを取得してください。

GDCubismが利用しているSDKバージョンは **Cubism 5 SDK for Native R2 beta2** です。

thirdpartyフォルダに展開した内容をそのまま配置してください。

展開すると以下のような配置となります。

[source]
----
./thirdparty
    /CubismSdkForNative-5-r.1-beta.2
        /Core
            /dll
            ...
        /Framework
            /build
            ...
----


==== CubismNativeFrameworkのカスタマイズ

GDCubismはCubismSdkForNativeに同梱されているCubismNativeFrameworkを使用していますが、最新のFrameworkや独自に拡張したい場合は、以下の方法で変更可能です。

[source, bash]
----
pushd thirdparty
git clone https://github.com/Live2D/CubismNativeFramework.git
popd
----

CAUTION: ビルドはCubismSdkForNativeにあるFrameworkよりカスタムビルドの方が優先されます。
不要になりましたら削除を行ってください。


=== Windows版のビルド

[NOTE]
====
ビルドには以下のものが必要となります。

* link:https://visualstudio.microsoft.com/ja/vs/community/[VisualStudio Community], version 2019 or lator.
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====


環境が準備できたら以下の手順でビルドを行ってください。

[source, console]
--
scons platform=windows arch=x86_64 target=template_debug
scons platform=windows arch=x86_64 target=template_release
--

ビルドが完了すると以下のファイルが _demo/addons/gd_cubism/bin_ 以下に生成されます。

* libgd_cubism.windows.debug.x86_64.dll
* libgd_cubism.windows.release.x86_64.dll


=== macOS版のビルド

ビルドには以下のものが必要となります。

[NOTE]
====
* link:https://apps.apple.com/us/app/xcode/id497799835[Xcode]
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====

準備できたら以下の手順でビルドを行ってください。

[source, bash]
--
# for x86_64(intel mac)
scons platform=macos arch=x86_64 target=template_debug
scons platform=macos arch=x86_64 target=template_release
# for arm64(Apple Silicon mac)
scons platform=macos arch=arm64 target=template_debug
scons platform=macos arch=arm64 target=template_release
--

ビルドが完了すると以下のファイルが _demo/addons/gd_cubism/bin_ 以下に生成されます。

* libgd_cubism.macos.debug.framework
* libgd_cubism.macos.release.framework


==== universalバイナリとしてビルドする場合

universalバイナリとしてビルドする場合は、sconsを実行する前に以下の様にリンクファイルを生成してください。

[source, bash]
----
pushd thirdparty/CubismSdkForNative-5-r.1-beta.2/Core/lib/macos
mkdir universal
lipo -create arm64/libLive2DCubismCore.a x86_64/libLive2DCubismCore.a -output universal/libLive2DCubismCore.a
popd

# for universal
scons platform=macos arch=universal target=template_debug
scons platform=macos arch=universal target=template_release
----


=== Linux版のビルド

[NOTE]
====
ビルドには以下のものが必要となります。

* GCC 7+, Clang 6+.
* link:https://www.python.org/downloads/windows/[Python 3.6+].
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.

Linuxの場合、ディストリビューション毎に必要なパッケージが追加で必要となる場合があります。どのディストリビューションで何が必要になるかは Godot Engine のドキュメントを参考にしてください。

* link:https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html[Compiling for Linux, *BSD]
====


環境が準備できたら以下の手順でビルドを行ってください。

[source, bash]
--
scons platform=linux arch=x86_64 target=template_debug
scons platform=linux arch=x86_64 target=template_release
--

ビルドが完了すると以下のファイルが _demo/addons/gd_cubism/bin_ 以下に生成されます。

* libgd_cubism.linux.debug.x86_64.so
* libgd_cubism.linux.release.x86_64.so


=== その他のビルドについて

以下の二つはビルドが行えることのみを確認しており、動作確認まではしていません。

それぞれの環境で動かしてみる場合の参考にご利用ください。


==== iOS版のビルド

ビルドには以下のものが必要となります。

[NOTE]
====
* link:https://apps.apple.com/us/app/xcode/id497799835[Xcode]
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====

Xcodeはコマンドラインのみで使用している場合、iphoneos向けのビルドが開始されない場合があります。

この場合はXcodeのパスを以下の様に指定し直すことでビルドが行われる様になります。

[source, bash]
----
sudo xcode-select --switch /Applications/Xcode.app 
----

準備できたら以下の手順でビルドを行ってください。

[source, bash]
--
# for arm64
scons platform=ios arch=arm64 target=template_debug
scons platform=ios arch=arm64 target=template_release
# for universol
scons platform=ios arch=universal target=template_debug
scons platform=ios arch=universal target=template_release
--

ビルドが完了すると以下のファイルが _demo/addons/gd_cubism/bin_ 以下に生成されます。

* libgd_cubism.ios.debug.arm64.dylib
* libgd_cubism.ios.release.arm64.dylib
* libgd_cubism.ios.debug.universal.dylib
* libgd_cubism.ios.release.universal.dylib


==== Android版のビルド

