= Cubism for GDScript
:lang: ja
:doctype: book
:author: MizunagiKB
:toc: left
:toclevels: 3
:source-highlighter: highlight.js
:highlightjsdir: res/theme/css
:highlightjs-theme: github-dark-custom
:icons: font
:experimental:
:stem:


== ビルド方法について


=== ビルド前の準備


==== ビルドに必要なソースコードの取得

GDCubismのリポジトリからソースコードを取得してください。

submoduleを使用していますので、git cloneした場合は ```git submodule update --init``` を行ってください。

zipファイルでダウンロードした場合は、git submoduleがうまく動作しない可能性があります。

その場合は手動でgit submoduleで追加を行ってください。

[source,zsh]
--
# GDExtensionを作成するためのヘッダファイル
git submodule add -b 4.1 https://github.com/godotengine/godot-cpp
pushd godot-cpp
git submodule update --init
popd
--


==== CubismSdkForNativeの入手と配置

Live2D Cubism SDK for Nativeを取得してください。

GDCubismが使用しているSDKバージョンは**Cubism 5 SDK for Native R1 beta1**となります。

ダウンロードしたファイルはthirdparty/CubismSdkForNativeに展開してください。

展開すると以下のような配置になるはずです。

[source]
----
./thirdparty
    /CubismNativeFramework
        /Core
            /dll
            ...
        /Framework
            /build
            ...
----


== ビルド方法


=== Windows

[NOTE]
====
ビルドには以下のものが必要となります。

* link:https://visualstudio.microsoft.com/ja/vs/community/[VisualStudio Community], version 2019 or lator.
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====


環境が準備できたら以下の手順でビルドを行ってください。

[source]
--
scons platform=windows target=template_debug
scons platform=windows target=template_release
--

ビルドが完了すると以下のファイルがdemo/addons/gd_cubism/bin以下に生成されます。

* libgd_cubism.windows.debug.x86_64.dll
* libgd_cubism.windows.release.x86_64.dll


=== macOS

[NOTE]
====
ビルドには以下のものが必要となります。

* link:https://apps.apple.com/us/app/xcode/id497799835[Xcode]
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====

Live2D Cubism SDK for Nativeはx86_64とarm64向けにライブラリが用意されているのですが、アーキテクチャ別にファイルが配置されているためmacOS向けのuniversalバイナリが作成しづらいです。

ビルドしやすい様に、それら二つのファイルを結合してしまいます。

[source,zsh]
--
pushd thirdparty/CubismSdkForNative/Core/lib/macos
# for Universal Binary
lipo -create arm64/libLive2DCubismCore.a x86_64/libLive2DCubismCore.a -output libLive2DCubismCore.universal.a
popd
--

環境が準備できたら以下の手順でビルドを行ってください。

[source,zsh]
--
scons platform=macos target=template_debug
scons platform=macos target=template_release
--

ビルドが完了すると以下のファイルがdemo/addons/gd_cubism/bin以下に生成されます。

* libgd_cubism.macos.debug.framework
* libgd_cubism.macos.release.framework


== Linux

[NOTE]
====
ビルドには以下のものが必要となります。

* GCC 7+, Clang 6+.
* link:https://www.python.org/downloads/windows/[Python 3.6+].
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====


Linuxの場合、ディストリビューション毎に必要なパッケージが追加で必要となる場合があります。どのディストリビューションで何が必要になるかは Godot Engine のドキュメントを参考にしてください。

* link:https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html[Compiling for Linux, *BSD]


環境が準備できたら以下の手順でビルドを行ってください。

[source,zsh]
--
scons platform=linux target=template_debug
scons platform=linux target=template_release
--

ビルドが完了すると以下のファイルがdemo/addons/gd_cubism/bin以下に生成されます。

* libgd_cubism.linux.debug.x86_64.so
* libgd_cubism.linux.release.x86_64.so


== デバッグ方法


=== macOS

GDCubismのデバッグを行うにはVisualStudio Codeを使用して以下の方法で行えます。

1. SConsのビルド時にdebug_symbols=true optimize=noneを追加します。
2. launch.jsonに以下を追加します。
3. Godotでdemoプロジェクトを開きExportを行います。
4. デバッグ実行を行います。

[source.json]
--
{
    "name": "Debug (macOS)",
    "type":"cppdbg",
    "request": "launch",
    "program": "${workspaceRoot}/demo.export/demo.app/Contents/MacOS/demo",
    "stopAtEntry": false,
    "launchCompleteCommand": "exec-run",
    "osx": {
        "MIMode": "lldb"
    },
    "cwd": "${workspaceRoot}/demo.export",
}
--

