= Cubism for GDScript
:author: MizunagiKB
:copyright: 2023 MizunagiKB <mizukb@live.jp>
:doctype: book
:toc:
:toclevels: 3
:lang: en
:encoding: utf-8
:stylesdir: ./res/theme/css
:stylesheet: adoc-golo.css
:source-highlighter: highlight.js
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


link:BUILD.adoc[Japanese] / link:BUILD.en.adoc[English]


== How to build
=== Preparation before building
==== Get source code

Get the source code from the GDCubism repository.

[source, zsh]
----
git clone https://github.com/MizunagiKB/gd_cubism.git
cd gd_cubism
git submodule update --init
----


==== Preparation of CubismSdkForNative

. Get Live2D Cubism SDK for Native.
.. The SDK version used by GDCubism is **Cubism 5 SDK for Native R1 beta2**.
.. Get Cubism 5 SDK for Native from Live2D's official website.
. Extract the downloaded file to _thirdparty_.

When expanded, it should look like the following.

[source, console]
----
./thirdparty
    /CubismSdkForNative-5-r.1-beta.2
        /Core
            /dll
            ...
        /Framework
            /build
            ...
----


This is a possible translation of the text in English:

==== Customizing CubismNativeFramework

GDCubism uses CubismNativeFramework, which is included in CubismSdkForNative. If you want to use the latest Framework or customize it for your own needs, you can do so by following these steps:

[source, bash]
----
pushd thirdparty
git clone https://github.com/Live2D/CubismNativeFramework.git
popd
----

CAUTION: This build has priority over the Framework in CubismSdkForNative, so please delete it when it is no longer needed.


=== Build for Windows

[NOTE]
====
The following items are required for building:

* link:https://visualstudio.microsoft.com/ja/vs/community/[VisualStudio Community], version 2019 or lator.
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====


When ready, run the build with the following command.

[source]
--
scons platform=windows arch=x86_64 target=template_debug
scons platform=windows arch=x86_64 target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.windows.debug.x86_64.dll
* libgd_cubism.windows.release.x86_64.dll


=== Build for macOS

[NOTE]
====
The following items are required for building:

* link:https://apps.apple.com/us/app/xcode/id497799835[Xcode]
* link:https://www.python.org/downloads/windows/[Python 3.6+]
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.
====

When ready, run the build with the following command.

[source, bash]
--
# for x86_64(intel mac)
scons platform=macos arch=x86_64 target=template_debug
scons platform=macos arch=x86_64 target=template_release
# for arm64(Apple Silicon mac)
scons platform=macos arch=arm64 target=template_debug
scons platform=macos arch=arm64 target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.macos.debug.framework
* libgd_cubism.macos.release.framework


==== Building as a universal binary

If you want to build as a universal binary, you need to create link files as follows before running scons.


[source, bash]
----
pushd thirdparty/CubismSdkForNative-5-r.1-beta.2/Core/lib/macos
mkdir universal
lipo -create arm64/libLive2DCubismCore.a x86_64/libLive2DCubismCore.a -output universal/libLive2DCubismCore.a
popd

# for universal
scons platform=macos arch=universal target=template_debug
scons platform=macos arch=universal target=template_release
----


=== Build for Linux

[NOTE]
====
The following items are required for building:

* GCC 7+, Clang 6+.
* link:https://www.python.org/downloads/windows/[Python 3.6+].
* link:https://scons.org/pages/download.html[SCons 3.0+] build system.

For Linux, additional packages may be required for each distribution. Please refer to the Godot Engine documentation to find out what distributions require. (I checked on Ubuntu 22.04 Desktop)

* link:https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html[Compiling for Linux, *BSD]
====


When ready, run the build with the following command.

[source, bash]
--
scons platform=linux target=template_debug
scons platform=linux target=template_release
--

When the build is completed, the following files will be generated under _demo/addons/gd_cubism/bin_.

* libgd_cubism.linux.debug.x86_64.so
* libgd_cubism.linux.release.x86_64.so
