# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2023 MizunagiKB <mizukb@live.jp>
import sys
import os
from glob import glob
from pathlib import Path


Import("env")
ext_env = env.Clone()

print("")
print("--- GDCubism Extension(s) ---")
print("")


# Add source files.
ext_env.Append(CPPPATH=["gd_cubism_motion_importer/"])


print("          WITH_GDCUBISM_EXT = {:s}".format(ARGUMENTS.get("WITH_GDCUBISM_EXT", "0")))
print("                   platform = {:s}".format(ext_env["platform"]))
print("                       arch = {:s}".format(ext_env["arch"]))


print("")

sources = glob("gd_cubism_motion_importer/*.cpp")


(extension_path,) = glob("../demo/addons/gd_cubism_motion_importer/*.gdextension*")

addon_path = Path(extension_path).parent
project_name = Path(extension_path).stem

debug_or_release = "release" if ext_env["target"] == "template_release" else "debug"
if ext_env["platform"] == "macos":
    library = ext_env.SharedLibrary(
        "{0}/bin/lib{1}.{2}.{3}.framework/{1}.{2}.{3}".format(
            addon_path,
            project_name,
            ext_env["platform"],
            debug_or_release,
        ),
        source=sources,
    )
else:
    library = ext_env.SharedLibrary(
        "{}/bin/lib{}.{}.{}.{}{}".format(
            addon_path,
            project_name,
            ext_env["platform"],
            debug_or_release,
            ext_env["arch"],
            ext_env["SHLIBSUFFIX"],
        ),
        source=sources,
    )

ext_env.Default(library)
