= Custom Animation
:encoding: utf-8
:lang: en
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2024 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ./docs/res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


xref:ja/custom/animation.adoc[Japanese] / xref:en/custom/animation.adoc[English]


[NOTE]
====
この文書は執筆中です。
====


== はじめに

GDCubism は Godot Engine 上で Live2D モデルを再生する事を簡単に目的に開発されています。

SubViewport経由で描画を行なっているため、モデル表示までは少し手間ですが、一旦表示まで行えば Godot Editor 上から簡単に確認できる様にしています。

簡単に表示が行える一方で、より細かい制御を行いたい場合にどうすれば良いのかというのがややわかりづらいものになっています。例えば、モーションの再生をさせつつ一部のパラメータのみを変更したいといった場合です。

その様な操作は GDScript を使用する事で実現できるのですが、現状ソースコードを読む事でしか気がつけません。

そのため、資料としてこのドキュメントを執筆しました。


=== 処理の流れについて

GDScript で Live2D モデルを制御する場合、 GDCubismUserModel の get_parameter 関数で取得する配列を制御することになりますが、何も考えずに設定しても Live2D モデルにうまく反映されません。

その理由はパラメータを上書きしようとしても、設定されているモーションが上書きをしてしまう事が原因です。

うまく設定するには GDCubism がどの様に描画をおこなっているかを知るっておく方が良いかと思いますので、まずは GDCubism がどのように Live2D モデルを描画しているかについて説明します。（技術的な背景に興味がない方は読み飛ばしてください）


==== 処理についての説明

GDCubismUserModel は以下の処理を毎フレーム行います。順番の大枠は「設定値の読込」「Live2D情報の更新」「描画」となります。

. 設定値の読込
.. モーションパラメータを更新。
.. エクスプレッションパラメータを更新。
.. GDCubismUserModel の parameters を反映。
.. GDCubismUserModel の opacities を反映。
. Live2D情報の更新
.. 物理パラメータを更新。
.. ポーズを更新。
.. 描画情報を更新。
. 描画情報の作成
.. 描画に必要な SubViewport と Mesh 数を計算。
.. SubViewport と ArrayMesh を生成し、ノードツリーに割り当て。

> 実際のプログラムコード（0.6時点）では、 _process をトリガとして以下の様に呼び出されています。

NOTE: _process は playback_process_mode が IDLE に設定されている場合です。 PHYSICS の場合は _physics_process、 MANUAL の場合は  _advance となります。


* _GDCubismUserModel_._process
** _GDCubismUserModel_._update

*** _InternalCubismModel_.pro_update
**** _InternalCubismModel_.effect_batch
***** *cubism_prologue* シグナルの呼び出し
**** Live2D モデルのパラメータ情報を復元
**** _motionManager.UpdateMotion
**** Live2D モデルのパラメータ情報を保存
**** _expressionManager.UpdateMotion
**** _InternalCubismModel_.GetModelOpacity

*** _InternalCubismModel_.efx_update
**** GDCubismEffect*ノードに変更があれば、 efx_term, efx_init シグナルの呼び出しfootnote:id[ここで呼び出されると、シグナルが中途半端に呼び出されてしまうため、今後のバージョンで呼び出し位置が変更される可能性があります。]
**** _InternalCubismModel_.effect_batch
***** *cubism_process* シグナルの呼び出し

*** パラメータ情報の設定と取得
*** 透明度の設定と取得

*** _InternalCubismModel_.epi_update
**** Live2D モデルの物理パラメータを更新
**** Live2D モデルのポーズを更新
**** Live2D モデルの内部状態を更新
**** _InternalCubismModel_.effect_batch
***** *cubism_epilogue* シグナルの呼び出し

*** _InternalCubismModel_.update_node
**** _InternalCubismModel_.GetRenderer
**** 描画サイズの反映
**** 描画位置の反映
**** 描画に必要なリソースの確保
**** 描画に必要な情報を GodotEngine に設定


==== 任意の処理を追加する方法

ここからは実際にどう処理すれば良いかについて記述していきます。


===== _process 関数内で処理する方法

前述した一連の処理は、すべて Godot Engine が GDCubismUserModel の _process を呼び出すタイミングで行われます。

そのため、少しだけ Live2D モデルのパラメータを変更したい場合は、その後で行えばよいことになります。注意点としては Godot Engine 側が GDCubismUserModel 内の _process が呼び出されるのがいつなのかという事です。

これは GDCubismUserModel がノードツリーのどの場所にあり、スクリプトがどこに設定されているかによります。確実に反映させるには、 GDCubismUserModel の playback_process_mode を MANUAL にして、 advance 関数を呼び出してからパラメータを操作するようにしてください。

これにより、パラメータの更新が反映前に上書きされてしまうのを防ぐ事が出来ます。

[source]
[source,,numlines]
----
include::example$custom_animation_process.gd[]
----


===== GDCubismEffectCustom で処理する方法

GDCubismUserModel の子要素に GDCubismEffectCustom を追加すると、cubism_prologue, cubism_process, cubism_epilogue シグナルが受け取れるようになります。


GDCubismEffectCustom が受け取る事ができるシグナルは5種類ありますが、そのうち Live2D モデルに関するものは以下の3種類となります。

cubism_prologue::
Live2Dモデルに適用されたモーションとエクスプレッションの更新前に呼び出されます。このシグナルを受けった際にパラメータ変更を行なっても無視されてしまいます。
 +
現在は GDCubismUserModel の get_parameters 関数で取得したパラメータに対して操作出来てしまいますが、将来のバージョンで挙動が変わる可能性があります。

cubism_process::
Live2Dモデルに適用されたモーションとエクスプレッションが更新された後に呼び出されます。このシグナルを受け取ったタイミングでパラメータを更新すると、モーションを再生させながら任意の処理を上書き出来ます。

例えば、手の形を差し替える、帽子を外す、目を閉じるといった処理です。


cubism_epilogue::
cubism_process とほとんど同じですが、GDCubismUserModel の get_parameters の内容がモーションとエクスプレッションを反映させた状態になっています。

[source]
[source,,numlines]
----
include::example$custom_animation_signal.gd[]
----


== サンプルコードについて

GDCubismEffectCustom を使用したサンプルとして以下のものが用意されています。


[cols="1,1",frame=none,grid=none]
|===
^|Name ^|Desc

|demo_effect_custom_01.tscn
|_GDCubismEffectCustom_ を使用したサンプルとなります。

|demo_effect_custom_02.tscn
|_GDCubismEffectCustom_ を使用したサンプルとなります。

|demo_effect_custom_03.tscn
|_GDCubismEffectCustom_ を使用したサンプルとなります。
簡易的なリップシンクを行なって、音量にあわせて口を動かしています。

|===
