= GDCubismEffectTargetPoint
:encoding: utf-8
:lang: en
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ../../res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


== Desc

By placing it as a child element of xref:./gd_cubism_user_model.adoc[], you can make the face and eyes look at the specified coordinates.

NOTE: You need to pre-configure the Live2D model to use this element.

If you want to move the eyes to the position where you drag the mouse pointer on the screen, use the following code to update the current position to _GDCubismEffectTargetPoint_.


[source, gdscript, numlines]
----
func _input(event):
    if event as InputEventMouseButton:
        pressed = event.is_pressed()

    if event as InputEventMouseMotion:
        if pressed == true:
            var calc_pos: Vector2 = $GDCubismUserModel.to_local(event.position) * Vector2(1, -1)
            $GDCubismUserModel/GDCubismEffectTargetPoint.set_target(calc_pos.normalized())
        else:
            $GDCubismUserModel/GDCubismEffectTargetPoint.set_target(Vector2.ZERO)
----


== Properties

[cols="3", frame=none, grid=none]
|===
>|String <|<<id-property-body_angle_x,body_angle_x>> |[default: "ParamBodyAngleX"]
>|float <|<<id-property-body_range,body_range>> |[default: 10.0]

>|String <|<<id-property-eyes_ball_x,eyes_ball_x>> |[default: "ParamEyeBallX"]
>|String <|<<id-property-eyes_ball_y,eyes_ball_y>> |[default: "ParamEyeBallX"]
>|float <|<<id-property-eyes_range,eyes_range>> |[default: 1.0]

>|String <|<<id-property-head_angle_x,head_angle_x>> |[default: "ParamAngleX"]
>|String <|<<id-property-head_angle_y,head_angle_y>> |[default: "ParamAngleY"]
>|String <|<<id-property-head_angle_z,head_angle_z>> |[default: "ParamAngleZ"]
>|float <|<<id-property-head_range,head_range>> |[default: 30.0]
|===


== Methods

[cols="2",frame=none,grid=none]
|===
>|Vector2 <|get_target()
>|void <|set_target(target: Vector2)
|===


== Signals
== Enumerations
== Constants
== Property Descriptions

[[id-property-body_angle_x]]
String body_angle_x [default: "ParamBodyAngleX"]::
Specifies the _ID_ used to change the orientation of the body with set_target.

[[id-property-body_range]]
String body_range [default: 10.0]::
Specifies how much to move the _ID_ specified with _body_angle_x_. +
The larger the value, the more sensitive the response, and if you specify 0.0, it will not respond.

[[id-property-eyes_ball_x]]
String eyes_ball_x [default: "ParamEyeBallX"]::
Specifies the _ID_ used to change the line of sight (direction of the pupil) with set_target.

[[id-property-eyes_ball_y]]
String eyes_ball_y [default: "ParamEyeBallX"]::
Specifies the _ID_ used to change the line of sight (direction of the pupil) with set_target.

[[id-property-eyes_range]]
String eyes_range [default: 1.0]::
Specifies how much to move the _ID_ specified with _eyes_ball_x_, _eyes_ball_x_. +
The larger the value, the more sensitive the response, and if you specify 0.0, it will not respond.

[[id-property-head_angle_x]]
String head_angle_x [default: "ParamHeadAngleX"]::
Specifies the _ID_ used to change the line of sight (direction of the pupil) with set_target.

[[id-property-head_angle_y]]
String head_angle_y [default: "ParamHeadAngleY"]::
Specifies the _ID_ used to change the line of sight (direction of the pupil) with set_target.

[[id-property-head_angle_z]]
String head_angle_z [default: "ParamHeadAngleZ"]::
Specifies the _ID_ used to change the line of sight (direction of the pupil) with set_target.

[[id-property-head_range]]
String head_range [default: 3.0]::
Specifies how much to move the _ID_ specified with _head_angle_x_, _head_angle_y_, _head_angle_z_. +
The larger the value, the more sensitive it responds, and if you specify 0.0, it will not respond.


== Method Descriptions

[[id-method-get_target]]
Vector2 get_target()::
Gets the direction the Live2D model is facing.

[[id-method-set_target]]
void set_target(target: Vector2)::
Sets the direction the Live2D model is facing. +
The direction that can be set is in the range of -1.0 to 1.0 for both x and y. +
If you pass a value that exceeds the range, it will be contained within the range. +
+ 
The coordinates to specify are not the coordinates of the screen, but the range from the center of the Node where the texture is pasted. +

* x: 0.0, y: 0.0 Front
* x: -1.0, y: 0.0 Screen left
* x: 1.0, y: 0.0 Screen right
* x: 0.0, y: -1.0 Screen bottom
* x: 0.0, y: 1.0 Screen top

