= GDCubismUserModel
:encoding: utf-8
:lang: en
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ../../res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


== Desc

This is a _SubViewport_ subclass for loading the Live2D model, generating the _Texture_ necessary for display, and performing operations.



== Properties

[cols="3",frame=none,grid=none]
|===
>|Vector2 <|<<id-property-adjust_position,adjust_position>> |[default: Vector2(0, 0)]
>|float <|<<id-property-adjust_scale,adjust_scale>> |[default: 1.0]
>|String <|<<id-property-assets,assets>> |[default: ""]
>|bool <|<<id-property-auto_scale,auto_scale>> |[default: true]
>|bool <|<<id-property-load_expressions,load_expressions>> |[default: true]
>|bool <|<<id-property-load_motions,load_motions>> |[default: true]
>|Vector2i <|<<id-property-mask_viewport_size,mask_viewport_size>> |[default: Vector2i(0, 0)]
>|ParameterMode <|<<id-property-parameter_mode,parameter_mode>> |[default: 0]
>|bool <|<<physics_evaluate>> |[default: true]
>|MotionProcessCallback <|<<id-property-playback_process_mode,playback_process_mode>> |[default: 1]
>|bool <|<<pose_update>> |[default: true]
>|Shader <|<<id-property-shader_add,shader_add>> |
>|Shader <|<<id-property-shader_mask,shader_mask>> |
>|Shader <|<<id-property-shader_mask_add,shader_mask_add>> |
>|Shader <|<<id-property-shader_mask_add_inv,shader_mask_add_inv>> |
>|Shader <|<<id-property-shader_mask_mix,shader_mask_mix>> |
>|Shader <|<<id-property-shader_mask_mix_inv,shader_mask_mix_inv>> |
>|Shader <|<<id-property-shader_mask_mul,shader_mask_mul>> |
>|Shader <|<<id-property-shader_mask_mul_inv,shader_mask_mul_inv>> |
>|Shader <|<<id-property-shader_mix,shader_mix>> |
>|Shader <|<<id-property-shader_mul,shader_mul>> |
>|float <|<<id-property-speed_scale,speed_scale>> |[default: 1.0]
|===


== Methods

[cols="2",frame=none,grid=none]
|===
>|void <|advance(delta: float)
>|void <|clear()
>|moc3FileFormatVersion <|csm_get_latest_moc_version()
>|moc3FileFormatVersion <|csm_get_moc_version()
>|Dictionary <|csm_get_version()
>|Dictionary <|get_canvas_info()
>|Array <|get_cubism_motion_queue_entries()
>|Array <|get_expressions()
>|Array <|get_hit_areas()
>|Dictionary <|get_meshes()
>|Dictionary <|get_motions()
>|Array <|get_parameters()
>|Array <|get_part_opacities()
>|void <|start_expression(expression_id: String)
>|GDCubismMotionQueueEntryHandle <|start_motion(group: String, no: int, priority: Priority)
>|GDCubismMotionQueueEntryHandle <|start_motion_loop(group: String, no: int, priority: Priority, loop: bool, loop_fade_in: bool)
>|void <|stop_expression()
>|void <|stop_motion()
|===


== Signals

motion_event(value: String)::
Called at the timing of the event time embedded in _Motion_.

.Example
[source,gdscript]
----
func _on_motion_event(value: String):
    print(value)

func _ready():
    $GDCubismUserModel.motion_event.connect(_on_motion_event)
----

motion_finished()::
Called at the timing when _Motion_ has finished playing.

.Example
[source,gdscript]
----
func _on_motion_finished(value: String):
    print(value)

func _ready():
    $GDCubismUserModel.motion_event.connect(_on_motion_event)
----



== Enumerations

[[id-enum-moc3_file_format_version]]
enum moc3FileFormatVersion::
* CSM_MOC_VERSION_UNKNOWN = 0 +
Unknown or failed to load
* CSM_MOC_VERSION_30 = 1 +
moc3 file version from 3.0.00 to 3.2.07
* CSM_MOC_VERSION_33 = 2 +
moc3 file version from 3.3.00 to 3.3.03
* CSM_MOC_VERSION_40 = 3 +
moc3 file version from 4.0.00 to 4.1.05
* CSM_MOC_VERSION_42 = 4 +
moc3 file version from 4.2.00 to 4.2.02
* CSM_MOC_VERSION_50 = 5 +
moc3 file version 5.0.00 and above

[[id-enum-priority]]
enum Priority::
* PRIORITY_NONE = 0
* PRIORITY_IDLE = 1
* PRIORITY_NORMAL = 2
* PRIORITY_FORCE = 3 +
Switches forcibly.

[[id-enum-parameter_mode]]
enum ParameterMode::
* FULL_PARAMETER = 0 +
Specify this when playing the _Motion_ specified by the <<id-method-start_motion,_start_motion_>> function. +
When this is specified, operations by xref:./gd_cubism_parameter.adoc[] cannot be performed.
* NONE_PARAMETER = 1 +
Specify this when using the xref:./gd_cubism_parameter.adoc[] obtained by the <<id-method-start_motion,_get_parameters_>> function to operate the Live2D model. +
When this is specified, motion playback cannot be performed by the <<id-method-start_motion,_start_motion_>> function.


[[id-enum-motion_process_callback]]
enum MotionProcessCallback::
* PHYSICS = 0 +
The animation update process is performed within the __physics_process_ function. Use this when you want to interact with physical simulation.
* IDLE = 1 +
The animation update process is performed within the __process_ function.
* MANUAL = 2 +
No animation update process is performed. To process the animation, use the <<id-method-advance,_advance_>> function.

I hope this helps! If you have any other requests, feel free to ask.


== Property Descriptions

[[id-property-adjust_position]]
Vector2 adjust_position [default: Vector2(0, 0)]::
Changes the rendering position of the Live2D model. +
GDCubism performs the rendering of the Live2D model within its own SubViewport. +
By adjusting this parameter, you can close-up a part of the Live2D model or use it when the auto_scale rendered result is not drawn well.


[[id-property-adjust_scale]]
float adjust_scale [default: 1.0]::
Changes the rendering size of the Live2D model. +
GDCubism performs the rendering of the Live2D model within its own SubViewport. +
By adjusting this parameter, you can freely change the rendering size of the Live2D model.


[[id-property-assets]]
String assets [default: ""]::
By specifying a file with the *.model3.json extension, you can load the Live2D model. As soon as you specify a file, it will be loaded immediately. +
if you want to switch the Live2D model, you can do so by simply specifying a new file.


[[id-property-auto_scale]]
bool auto_scale [default: true]::
_GDCubismUserModel_ tries to render the Live2D model to fit within the _SubViewport_ size specified for itself. Therefore, there may be results that the creator of the Live2D model did not intend. +
+
By unchecking this, you can display without scaling.


[[id-property-load_expressions]]
bool load_expressions [default: true]::
If set to _false_, it will not load _Expressions_ when loading the Live2D Model.


[[id-property-load_motions]]
bool load_motions [default: true]::
If set to _false_, it will not load _Motions_ when loading the Live2D Model.


[[id-property-mask_viewport_size]]
Vector2i mask_viewport_size [default: Vector2i(0, 0)]::
Specify the resolution for the mask image required for the Live2D model.
+
If either x or y is set to 0, the same size as the Viewport set in GDCubismUserModel will be used.
+
Reducing the resolution can help conserve GPU memory. +
However, if the size is reduced to less than approximately 512x512, there may be issues with rendering quality depending on where the mask is applied.
+
Ensure that the aspect ratio of this image matches the aspect ratio of the Viewport in GDCubismUserModel. For example, if it is _1024x512_, then values like _512x256_ or _128x64_ are appropriate.
+
Since GDCubism assumes the same aspect ratio as the Viewport for rendering, using an incorrect ratio may result in undesirable outcomes.


[[id-property-parameter_mode]]
ParameterMode parameter_mode [default: 0]::
Specifies the control method for the currently held Live2D model.


[[id-property-physics_evaluate]]
bool physics_evaluate [default: true]::
Setting this parameter to `false` disables physical calculations.


[[id-property-playback_process_mode]]
MotionProcessCallback playback_process_mode [default: 1]::
Specifies the playback method for the currently held Live2D model.


[[id-property-pose_update]]
bool pose_update [default: true]::
Setting this parameter to `false` disables transparency calculations between drawing parts specified in the pose group. +
If you want to manually handle all transparency calculations, set this parameter to `false`.


[[id-property-shader_add]]
Shader shader_add::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_norm_add.gdshader[]
----


[[id-property-shader_mask]]
Shader shader_mask::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask.gdshader[]
----


[[id-property-shader_mask_add]]
Shader shader_mask_add::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask_add.gdshader[]
----


[[id-property-shader_mask_add_inv]]
Shader shader_mask_add_inv::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask_add_inv.gdshader[]
----


[[id-property-shader_mask_mix]]
Shader shader_mask_mix::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask_mix.gdshader[]
----


[[id-property-shader_mask_mix_inv]]
Shader shader_mask_mix_inv::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask_mix_inv.gdshader[]
----


[[id-property-shader_mask_mul]]
Shader shader_mask_mul::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask_mul.gdshader[]
----


[[id-property-shader_mask_mul_inv]]
Shader shader_mask_mul_inv::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_mask_mul_inv.gdshader[]
----


[[id-property-shader_mix]]
Shader shader_mix::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_norm_mix.gdshader[]
----


[[id-property-shader_mul]]
Shader shader_mul::
Specifies the _shader_ used to render the Live2D model. +
By default, the following _shader_ is used.

[source,,numlines]
----
include::example$2d_cubism_norm_mul.gdshader[]
----


[[id-property-speed_scale]]
floats speed_scale [default: 1.0]::
Specifies the playback speed of the currently held Live2D model.


== Method Descriptions

[[id-method-advance]]
void advance(delta: float)::
Advances the animation by the specified _delta_ time (in seconds).
+
Please specify a value of 0.0 or more for delta.


[[id-method-clear]]
void clear()::
This function was removed to improve operational consistency. +
For similar operations, please set the _assets_ property to "".


[[id-method-csm_get_latest_moc_version]]
<<id-enum-moc3_file_format_version,moc3FileFormatVersion>> csm_get_latest_moc_version()::
Returns the latest file version that GDCubismUserModel can load.


[[id-method-csm_get_moc_version]]
<<id-enum-moc3_file_format_version,moc3FileFormatVersion>> csm_get_moc_version()::
Returns the version of the loaded moc3 file.


[[id-method-csm_get_version]]
Dictionary csm_get_version()::
Returns the version number of Cubism Native SDK Core used by GDCubism in _Dictionary_ format. +
+
version: int:::
The value returned by the _csmVersion_ function is stored as is.
major: int:::
Only the major version is extracted from version and stored.
minor: int:::
Only the minor version is extracted from version and stored.
patch: int:::
Only the patch number is extracted from version and stored.


[[id-method-get_canvas_info]]
Dictionary get_canvas_info()::
Returns the following information in _Dictionary_ format. +
+ 
size_in_pixels: Vector2:::
Returns the width and height of the canvas of the loaded Live2D model in pixels.
origin_in_pixels: Vector2:::
Returns the center position of the loaded Live2D model in pixels.
pixels_per_unit: float:::
Returns the _pixelsPerUnit_ of the loaded Live2D model.


[[id-method-get_cubism_motion_queue_entries]]
Array get_cubism_motion_queue_entries()::
Returns information about the currently playing _Motion_.


[[id-method-get_expressions]]
Array get_expressions()::
Returns a list of _Expressions_ from the currently held Live2D model.
+
The information obtained can be used as an argument for the _start_expression_ function.


[[id-method-get_hit_areas]]
Array get_hit_areas()::
Gets information about _HitArea_ set in Live2D model. +
The elements of array are _Dictionary_, and have elements _id_ and _name_. +
+
_id_ points to mesh element, so it can be used as a key for _get_meshes_. +
+
+
You can implement interaction with Live2D model using this function and information obtained from _get_meshes_. +
If you don't need advanced processing, you can easily use it by using _GDCubismEffectHitArea_ class.


[[id-method-get_meshes]]
Dictionary get_meshes()::
Gets information about _ArrayMesh_ of _MeshInstance_ used in current Motion state. +
+
The keys this _Dictionary_ holds are identical to names of _MeshInstance_ generated by _GDCubismUserModel_. The information that can be obtained is internal _ArrayMesh_. 
+
It can be used in following way.

[source, gdscript]
----
var dict_mesh: Dictionary = model.get_meshes()
var ary_mesh: ArrayMesh = dict_mesh[art_mesh_name]
var ary_surface: Array = ary_mesh.surface_get_arrays(0)

var mesh_vertex: PackedVector2Array = ary_surface[ArrayMesh.ARRAY_VERTEX]
var mesh_tex_uv: PackedVector2Array = ary_surface[ArrayMesh.ARRAY_TEX_UV]
var mesh_index: PackedInt32Array = ary_surface[ArrayMesh.ARRAY_INDEX]
----

CAUTION: get_meshes is an experimental function added in v0.1. Please note that the specification may change or be deleted in the future.


[[id-method-get_motions]]
Dictionary get_motions()::
Returns a list of _Motions_ from the currently held Live2D model. +
The returned _Dictionary_ is _group_ and the number of motions contained in it.
 +
 +
To enumerate all motions, write as follows.

[source, gdscript]
----
var dict_motion = $GDCubismUserModel.get_motions()
for group in dict_motion.keys():
    for no in dict_motion[group]:
        print("group: %s, no: %d" % [group, no])
----


[[id-method-get_parameters]]
Array get_parameters()::
Gets a class to operate the currently held Live2D model.


[[id-method-get_part_opacities]]
Array get_part_opacities()::
Gets a class to operate the part transparency of the currently held Live2D model.


[[id-method-start_expression]]
void start_expression(expression_id: String)::
Plays the specified _expression_id_.


[[id-method-start_motion]]
xref:./gd_cubism_motion_queue_entry_handle.adoc[] start_motion(group: String, no: int, priority: <<id-enum-priority,Priority>>)::
Plays the _Motion_ specified by _group_ and _no_.


[[id-method-start_motion_loop]]
xref:./gd_cubism_motion_queue_entry_handle.adoc[] start_motion_loop(group: String, no: int, priority: <<id-enum-priority,Priority>>)::
Plays the _Motion_ specified by _group_ and _no_. +
+
Specify this when you want to play repeatedly. If the _loop_ argument is _false_, it behaves the same as the _start_motion_ function.


[[id-method-stop_expression]]
void stop_expression()::
Stops the currently playing _Expression_.


[[id-method-stop_motion]]
void stop_motion()::
Stops the currently playing _Motion_.

