= GDCubismParameter
:encoding: utf-8
:lang: en
:author: MizunagiKB <mizukb@live.jp>
:copyright: 2023 MizunagiKB
:doctype: book
:source-highlighter: highlight.js
:icons: font
:experimental:
:stylesdir: ../../res/theme/css
:stylesheet: mizunagi-works.css
ifdef::env-github,env-vscode[]
:adocsuffix: .adoc
endif::env-github,env-vscode[]
ifndef::env-github,env-vscode[]
:adocsuffix: .html
endif::env-github,env-vscode[]


== Desc

Elements contained in the _Array_ returned by the _get_parameters_ function of xref:./gd_cubism_user_model.adoc[].

By writing a value to this class's _value_, you can modify the parameter of the Live2D model.



== Properties

[cols="3",frame=none,grid=none]
|===
>|float <|<<id-property-default_value,default_value>> |[default: 0.0]
>|bool <|<<id-property-hold,hold>> |[default: false]
>|float <|<<id-property-maximum_value,maximum_value>> |[default: 0.0]
>|float <|<<id-property-minimum_value,minimum_value>> |[default: 0.0]
|===


== Methods
[cols="2",frame=none,grid=none]
|===
>|void <|reset()
|===


== Enumerations
enum Type::
* NORMAL = 0
* BLEND_SHAPE = 1


== Property Descriptions

[[id-property-default_value]]
float default_value [default: 0.0]::
The initial value of the parameter held by this class.


[[id-property-maximum_value]]
float maximum_value [default: 0.0]::
The maximum value that can be set for the parameter held by this class.


[[id-property-minimum_value]]
float minimum_value [default: 0.0]::
The minimum value that can be set for the parameter held by this class.


[[id-property-hold]]
bool hold [default: false]::
If true, the parameters you set will take precedence even if motion or expression is set.


== Method Descriptions

[[id-method-reset]]
void reset()::
Resets the currently set value to _default_value_.
+
The hold status is also lifted.
